apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: simple-nodejs-app-etks
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: simple-nodejs-app-etks
    app.kubernetes.io/part-of: nodejs-users
  name: simple-nodejs-app-etks
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: simple-nodejs-app-etks
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: simple-nodejs-app-etks
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/e2e-demos-itsa-tenant/nodejs-users/simple-nodejs-app-etks@sha256:dd3a9c77d46f6ba3615742630c3cd9817a22e8a140e0a281d5bc2ea58a5bef71
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
